### ISSUE TITLE
Text not displaying on boot

### ISSUE THREAD

**Issue by rallepalaveev** [tjboldt/ProDOS-ROM-Drive#6]
I reviewed the code and have just a minor comment: $Cn26 should be "0D" and $CnEA should be "A0".

**Comment by tjboldt** [comment]
Thanks Ralle,

I see that because Y has changed to start at a non-zero value, this line had to be changed (which goes from DO to OD):

sta $07D0-<text,y ;put text on last line

The byte at $CnEA is the null terminator for the string so I'm not sure why it should be A0 which would be a space

See related pull request

**Comment by rallepalaveev** [comment]
It is the last character on the line and it prints inverted @

**Comment by tjboldt** [comment]
I updated this to instead not scribble over the scratch RAM but stop printing when null terminator reached.
